/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.CardLayout;

/**
 *
 * @author Ella
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainFrame() {
        initComponents();
        setUpView();
    }
    
    public final void setUpView(){
        setTitle("MainFrame");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainViewPanel = new javax.swing.JPanel();
        mainViewTitle = new javax.swing.JLabel();
        alterBudgetPanel = new javax.swing.JPanel();
        alterBudgetTitle = new javax.swing.JLabel();
        addExpensesPanel = new javax.swing.JPanel();
        addExpensesTitle = new javax.swing.JLabel();
        editExpensesPanel = new javax.swing.JPanel();
        editExpensesTitle = new javax.swing.JLabel();
        graphDataPanel = new javax.swing.JPanel();
        graphDataTitle = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        alterBudgetButton = new javax.swing.JButton();
        graphDataButton = new javax.swing.JButton();
        addExpensesButton = new javax.swing.JButton();
        editExpensesButton = new javax.swing.JButton();
        mainViewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");
        setName("Form"); // NOI18N

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.CardLayout());

        mainViewPanel.setName("mainViewPanel"); // NOI18N

        mainViewTitle.setText("Current Budget");
        mainViewTitle.setName("mainViewTitle"); // NOI18N

        javax.swing.GroupLayout mainViewPanelLayout = new javax.swing.GroupLayout(mainViewPanel);
        mainViewPanel.setLayout(mainViewPanelLayout);
        mainViewPanelLayout.setHorizontalGroup(
            mainViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainViewPanelLayout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(mainViewTitle)
                .addGap(220, 220, 220))
        );
        mainViewPanelLayout.setVerticalGroup(
            mainViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainViewTitle)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        mainPanel.add(mainViewPanel, "mainView");

        alterBudgetPanel.setName("alterBudgetPanel"); // NOI18N

        alterBudgetTitle.setText("Alter Budget Constraints");
        alterBudgetTitle.setName("alterBudgetTitle"); // NOI18N

        javax.swing.GroupLayout alterBudgetPanelLayout = new javax.swing.GroupLayout(alterBudgetPanel);
        alterBudgetPanel.setLayout(alterBudgetPanelLayout);
        alterBudgetPanelLayout.setHorizontalGroup(
            alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(alterBudgetTitle)
                .addGap(185, 185, 185))
        );
        alterBudgetPanelLayout.setVerticalGroup(
            alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterBudgetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alterBudgetTitle)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        mainPanel.add(alterBudgetPanel, "alterBudget");

        addExpensesPanel.setName("addExpensesPanel"); // NOI18N

        addExpensesTitle.setText("Add Expenses");
        addExpensesTitle.setName("addExpensesTitle"); // NOI18N

        javax.swing.GroupLayout addExpensesPanelLayout = new javax.swing.GroupLayout(addExpensesPanel);
        addExpensesPanel.setLayout(addExpensesPanelLayout);
        addExpensesPanelLayout.setHorizontalGroup(
            addExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addExpensesPanelLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(addExpensesTitle)
                .addGap(224, 224, 224))
        );
        addExpensesPanelLayout.setVerticalGroup(
            addExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addExpensesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addExpensesTitle)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        mainPanel.add(addExpensesPanel, "addExpenses");

        editExpensesPanel.setName("editExpensesPanel"); // NOI18N

        editExpensesTitle.setText("Edit Expenses Title");
        editExpensesTitle.setName("editExpensesTitle"); // NOI18N

        javax.swing.GroupLayout editExpensesPanelLayout = new javax.swing.GroupLayout(editExpensesPanel);
        editExpensesPanel.setLayout(editExpensesPanelLayout);
        editExpensesPanelLayout.setHorizontalGroup(
            editExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editExpensesPanelLayout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(editExpensesTitle)
                .addGap(210, 210, 210))
        );
        editExpensesPanelLayout.setVerticalGroup(
            editExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExpensesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editExpensesTitle)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        mainPanel.add(editExpensesPanel, "editExpenses");

        graphDataPanel.setName("graphDataPanel"); // NOI18N

        graphDataTitle.setText("Graph of Data");
        graphDataTitle.setName("graphDataTitle"); // NOI18N

        javax.swing.GroupLayout graphDataPanelLayout = new javax.swing.GroupLayout(graphDataPanel);
        graphDataPanel.setLayout(graphDataPanelLayout);
        graphDataPanelLayout.setHorizontalGroup(
            graphDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graphDataPanelLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(graphDataTitle)
                .addGap(228, 228, 228))
        );
        graphDataPanelLayout.setVerticalGroup(
            graphDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphDataTitle)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        mainPanel.add(graphDataPanel, "graphData");

        exitButton.setText("Exit");
        exitButton.setToolTipText("");
        exitButton.setName("exitButton"); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        alterBudgetButton.setText("Alter Budget Contraints");
        alterBudgetButton.setName("alterBudgetButton"); // NOI18N
        alterBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterBudgetButtonActionPerformed(evt);
            }
        });

        graphDataButton.setText("View Data as Graph");
        graphDataButton.setActionCommand("Add Expenditures");
        graphDataButton.setName("graphDataButton"); // NOI18N
        graphDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphDataButtonActionPerformed(evt);
            }
        });

        addExpensesButton.setText("Add Expenditures");
        addExpensesButton.setName("addExpensesButton"); // NOI18N
        addExpensesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpensesButtonActionPerformed(evt);
            }
        });

        editExpensesButton.setText("Edit Expenditures");
        editExpensesButton.setName("editExpensesButton"); // NOI18N
        editExpensesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExpensesButtonActionPerformed(evt);
            }
        });

        mainViewButton.setText("Main Screen");
        mainViewButton.setActionCommand("Add Expenditures");
        mainViewButton.setName("mainViewButton"); // NOI18N
        mainViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainViewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addExpensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alterBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editExpensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(graphDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alterBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addExpensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editExpensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(graphDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        mainPanel.getAccessibleContext().setAccessibleName("mainPanel");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterBudgetButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "alterBudget");
    }//GEN-LAST:event_alterBudgetButtonActionPerformed

    private void graphDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphDataButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "graphData");
    }//GEN-LAST:event_graphDataButtonActionPerformed

    private void addExpensesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpensesButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "addExpenses");
    }//GEN-LAST:event_addExpensesButtonActionPerformed

    private void editExpensesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExpensesButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "editExpenses");
    }//GEN-LAST:event_editExpensesButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void mainViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainViewButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mainView");
    }//GEN-LAST:event_mainViewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpensesButton;
    private javax.swing.JPanel addExpensesPanel;
    private javax.swing.JLabel addExpensesTitle;
    private javax.swing.JButton alterBudgetButton;
    private javax.swing.JPanel alterBudgetPanel;
    private javax.swing.JLabel alterBudgetTitle;
    private javax.swing.JButton editExpensesButton;
    private javax.swing.JPanel editExpensesPanel;
    private javax.swing.JLabel editExpensesTitle;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton graphDataButton;
    private javax.swing.JPanel graphDataPanel;
    private javax.swing.JLabel graphDataTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mainViewButton;
    private javax.swing.JPanel mainViewPanel;
    private javax.swing.JLabel mainViewTitle;
    // End of variables declaration//GEN-END:variables
}
