/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.CardLayout;

/**
 *
 * @author Ella
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainFrame() {
        initComponents();
        setUpView();
    }
    
    public final void setUpView(){
        setTitle("MainFrame");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainViewPanel = new javax.swing.JPanel();
        mainViewTitle = new javax.swing.JLabel();
        alterBudgetPanel = new javax.swing.JPanel();
        alterBudgetTitle = new javax.swing.JLabel();
        housingCheckBox = new javax.swing.JCheckBox();
        utilitiesCheckBox = new javax.swing.JCheckBox();
        groceriesCheckBox = new javax.swing.JCheckBox();
        transportationCheckBox = new javax.swing.JCheckBox();
        entertainmentCheckBox = new javax.swing.JCheckBox();
        miscCheckBox = new javax.swing.JCheckBox();
        housingInput = new javax.swing.JTextField();
        utilitiesInput = new javax.swing.JTextField();
        groceriesInput = new javax.swing.JTextField();
        entertainmentInput = new javax.swing.JTextField();
        transportationInput = new javax.swing.JTextField();
        categoriesLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        miscInput = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        addExpensesPanel = new javax.swing.JPanel();
        addExpensesTitle = new javax.swing.JLabel();
        editExpensesPanel = new javax.swing.JPanel();
        editExpensesTitle = new javax.swing.JLabel();
        graphDataPanel = new javax.swing.JPanel();
        graphDataTitle = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        alterBudgetButton = new javax.swing.JButton();
        graphDataButton = new javax.swing.JButton();
        addExpensesButton = new javax.swing.JButton();
        editExpensesButton = new javax.swing.JButton();
        mainViewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");
        setName("Form"); // NOI18N

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.CardLayout());

        mainViewPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainViewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainViewPanel.setName("mainViewPanel"); // NOI18N

        mainViewTitle.setText("Current Budget");
        mainViewTitle.setName("mainViewTitle"); // NOI18N

        javax.swing.GroupLayout mainViewPanelLayout = new javax.swing.GroupLayout(mainViewPanel);
        mainViewPanel.setLayout(mainViewPanelLayout);
        mainViewPanelLayout.setHorizontalGroup(
            mainViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainViewPanelLayout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(mainViewTitle)
                .addGap(220, 220, 220))
        );
        mainViewPanelLayout.setVerticalGroup(
            mainViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainViewTitle)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        mainPanel.add(mainViewPanel, "mainView");

        alterBudgetPanel.setBackground(new java.awt.Color(255, 255, 255));
        alterBudgetPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        alterBudgetPanel.setName("alterBudgetPanel"); // NOI18N

        alterBudgetTitle.setText("Alter Budget Constraints");
        alterBudgetTitle.setName("alterBudgetTitle"); // NOI18N

        housingCheckBox.setText("Housing/Rent");
        housingCheckBox.setName("housingCheckBox"); // NOI18N

        utilitiesCheckBox.setText("Utilities");
        utilitiesCheckBox.setName("utilitiesCheckBox"); // NOI18N
        utilitiesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilitiesCheckBoxActionPerformed(evt);
            }
        });

        groceriesCheckBox.setText("Groceries");
        groceriesCheckBox.setName("groceriesCheckBox"); // NOI18N

        transportationCheckBox.setText("Transportation");
        transportationCheckBox.setName("transportationCheckBox"); // NOI18N

        entertainmentCheckBox.setText("Entertainment");
        entertainmentCheckBox.setName("entertainmentCheckBox"); // NOI18N

        miscCheckBox.setText("Miscellaneous");
        miscCheckBox.setName("miscCheckBox"); // NOI18N

        housingInput.setName("housingInput"); // NOI18N

        utilitiesInput.setName("utilitiesInput"); // NOI18N

        groceriesInput.setName("groceriesInput"); // NOI18N
        groceriesInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groceriesInputActionPerformed(evt);
            }
        });

        entertainmentInput.setName("entertainmentInput"); // NOI18N

        transportationInput.setName("transportationInput"); // NOI18N
        transportationInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportationInputActionPerformed(evt);
            }
        });

        categoriesLabel.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        categoriesLabel.setText("Category to alter");
        categoriesLabel.setName("categoriesLabel"); // NOI18N

        amountLabel.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        amountLabel.setText("New Budget Amount");
        amountLabel.setName("amountLabel"); // NOI18N

        miscInput.setName("miscInput"); // NOI18N
        miscInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miscInputActionPerformed(evt);
            }
        });

        submitButton.setText("Submit Changes");
        submitButton.setName("submitButton"); // NOI18N

        javax.swing.GroupLayout alterBudgetPanelLayout = new javax.swing.GroupLayout(alterBudgetPanel);
        alterBudgetPanel.setLayout(alterBudgetPanelLayout);
        alterBudgetPanelLayout.setHorizontalGroup(
            alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterBudgetPanelLayout.createSequentialGroup()
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alterBudgetPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(housingCheckBox)
                            .addComponent(miscCheckBox)
                            .addComponent(transportationCheckBox)
                            .addComponent(entertainmentCheckBox)
                            .addComponent(groceriesCheckBox)
                            .addComponent(utilitiesCheckBox)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(categoriesLabel)
                        .addGap(15, 15, 15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                        .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(housingInput, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(utilitiesInput)
                            .addComponent(groceriesInput)
                            .addComponent(entertainmentInput)
                            .addComponent(transportationInput)
                            .addComponent(miscInput))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                        .addComponent(amountLabel)
                        .addGap(90, 90, 90))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                        .addComponent(alterBudgetTitle)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addGap(184, 184, 184))))
        );
        alterBudgetPanelLayout.setVerticalGroup(
            alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterBudgetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alterBudgetTitle)
                .addGap(18, 18, 18)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriesLabel)
                    .addComponent(amountLabel))
                .addGap(19, 19, 19)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housingCheckBox)
                    .addComponent(housingInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(utilitiesCheckBox)
                    .addComponent(utilitiesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groceriesCheckBox)
                    .addComponent(groceriesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entertainmentCheckBox)
                    .addComponent(entertainmentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportationCheckBox)
                    .addComponent(transportationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(miscCheckBox)
                    .addComponent(miscInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(22, 22, 22))
        );

        mainPanel.add(alterBudgetPanel, "alterBudget");

        addExpensesPanel.setBackground(new java.awt.Color(255, 255, 255));
        addExpensesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addExpensesPanel.setName("addExpensesPanel"); // NOI18N

        addExpensesTitle.setText("Add Expenses");
        addExpensesTitle.setName("addExpensesTitle"); // NOI18N

        javax.swing.GroupLayout addExpensesPanelLayout = new javax.swing.GroupLayout(addExpensesPanel);
        addExpensesPanel.setLayout(addExpensesPanelLayout);
        addExpensesPanelLayout.setHorizontalGroup(
            addExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addExpensesPanelLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(addExpensesTitle)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        addExpensesPanelLayout.setVerticalGroup(
            addExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addExpensesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addExpensesTitle)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        mainPanel.add(addExpensesPanel, "addExpenses");

        editExpensesPanel.setBackground(new java.awt.Color(255, 255, 255));
        editExpensesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editExpensesPanel.setName("editExpensesPanel"); // NOI18N

        editExpensesTitle.setText("Edit Expenses");
        editExpensesTitle.setName("editExpensesTitle"); // NOI18N

        javax.swing.GroupLayout editExpensesPanelLayout = new javax.swing.GroupLayout(editExpensesPanel);
        editExpensesPanel.setLayout(editExpensesPanelLayout);
        editExpensesPanelLayout.setHorizontalGroup(
            editExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editExpensesPanelLayout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(editExpensesTitle)
                .addGap(217, 217, 217))
        );
        editExpensesPanelLayout.setVerticalGroup(
            editExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExpensesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editExpensesTitle)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        mainPanel.add(editExpensesPanel, "editExpenses");

        graphDataPanel.setBackground(new java.awt.Color(255, 255, 255));
        graphDataPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        graphDataPanel.setName("graphDataPanel"); // NOI18N

        graphDataTitle.setText("Graph of Data");
        graphDataTitle.setName("graphDataTitle"); // NOI18N

        javax.swing.GroupLayout graphDataPanelLayout = new javax.swing.GroupLayout(graphDataPanel);
        graphDataPanel.setLayout(graphDataPanelLayout);
        graphDataPanelLayout.setHorizontalGroup(
            graphDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graphDataPanelLayout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(graphDataTitle)
                .addGap(217, 217, 217))
        );
        graphDataPanelLayout.setVerticalGroup(
            graphDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphDataTitle)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        mainPanel.add(graphDataPanel, "graphData");

        exitButton.setText("Exit");
        exitButton.setToolTipText("");
        exitButton.setName("exitButton"); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        alterBudgetButton.setText("Alter Budget Contraints");
        alterBudgetButton.setName("alterBudgetButton"); // NOI18N
        alterBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterBudgetButtonActionPerformed(evt);
            }
        });

        graphDataButton.setText("View Data as Graph");
        graphDataButton.setActionCommand("Add Expenditures");
        graphDataButton.setName("graphDataButton"); // NOI18N
        graphDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphDataButtonActionPerformed(evt);
            }
        });

        addExpensesButton.setText("Add Expenditures");
        addExpensesButton.setName("addExpensesButton"); // NOI18N
        addExpensesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpensesButtonActionPerformed(evt);
            }
        });

        editExpensesButton.setText("Edit Expenditures");
        editExpensesButton.setName("editExpensesButton"); // NOI18N
        editExpensesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExpensesButtonActionPerformed(evt);
            }
        });

        mainViewButton.setText("Main Screen");
        mainViewButton.setActionCommand("Add Expenditures");
        mainViewButton.setName("mainViewButton"); // NOI18N
        mainViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainViewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addExpensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alterBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editExpensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(graphDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alterBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addExpensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editExpensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(graphDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        mainPanel.getAccessibleContext().setAccessibleName("mainPanel");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterBudgetButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "alterBudget");
    }//GEN-LAST:event_alterBudgetButtonActionPerformed

    private void graphDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphDataButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "graphData");
    }//GEN-LAST:event_graphDataButtonActionPerformed

    private void addExpensesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpensesButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "addExpenses");
    }//GEN-LAST:event_addExpensesButtonActionPerformed

    private void editExpensesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExpensesButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "editExpenses");
    }//GEN-LAST:event_editExpensesButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void mainViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainViewButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mainView");
    }//GEN-LAST:event_mainViewButtonActionPerformed

    private void utilitiesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilitiesCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilitiesCheckBoxActionPerformed

    private void groceriesInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groceriesInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groceriesInputActionPerformed

    private void transportationInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportationInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportationInputActionPerformed

    private void miscInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miscInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miscInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpensesButton;
    private javax.swing.JPanel addExpensesPanel;
    private javax.swing.JLabel addExpensesTitle;
    private javax.swing.JButton alterBudgetButton;
    private javax.swing.JPanel alterBudgetPanel;
    private javax.swing.JLabel alterBudgetTitle;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JButton editExpensesButton;
    private javax.swing.JPanel editExpensesPanel;
    private javax.swing.JLabel editExpensesTitle;
    private javax.swing.JCheckBox entertainmentCheckBox;
    private javax.swing.JTextField entertainmentInput;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton graphDataButton;
    private javax.swing.JPanel graphDataPanel;
    private javax.swing.JLabel graphDataTitle;
    private javax.swing.JCheckBox groceriesCheckBox;
    private javax.swing.JTextField groceriesInput;
    private javax.swing.JCheckBox housingCheckBox;
    private javax.swing.JTextField housingInput;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mainViewButton;
    private javax.swing.JPanel mainViewPanel;
    private javax.swing.JLabel mainViewTitle;
    private javax.swing.JCheckBox miscCheckBox;
    private javax.swing.JTextField miscInput;
    private javax.swing.JButton submitButton;
    private javax.swing.JCheckBox transportationCheckBox;
    private javax.swing.JTextField transportationInput;
    private javax.swing.JCheckBox utilitiesCheckBox;
    private javax.swing.JTextField utilitiesInput;
    // End of variables declaration//GEN-END:variables
}
