package Forms;

import ItsCommonCents.InputValidator;
import ItsCommonCents.InputFilter;
import DataManagement.DataHandler;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;

public class SettingsInitializer extends javax.swing.JFrame {

    private ArrayList<javax.swing.JTextField> componentList;
    
    public SettingsInitializer() {
        initComponents();
        putInputComponentsInList();
        formatInputComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        housingLabel = new javax.swing.JLabel();
        utilitiesLabel = new javax.swing.JLabel();
        groceriesLabel = new javax.swing.JLabel();
        entertainmentLabel = new javax.swing.JLabel();
        miscellaneousLabel = new javax.swing.JLabel();
        transportationLabel = new javax.swing.JLabel();
        housingInput = new javax.swing.JTextField();
        utilitiesInput = new javax.swing.JTextField();
        entertainmentInput = new javax.swing.JTextField();
        transportationInput = new javax.swing.JTextField();
        miscellaneousInput = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        groceriesInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Budget Settings");

        housingLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        housingLabel.setText("Housing/Rent");

        utilitiesLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        utilitiesLabel.setText("Utilities");

        groceriesLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        groceriesLabel.setText("Groceries:");

        entertainmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        entertainmentLabel.setText("Entertainment:");

        miscellaneousLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        miscellaneousLabel.setText("Miscellaneous:");

        transportationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        transportationLabel.setText("Transportation:");

        saveButton.setText("Save");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        titleLabel.setText("Enter monthly budget for each spending category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(saveButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(entertainmentLabel)
                                .addComponent(groceriesLabel)
                                .addComponent(utilitiesLabel)
                                .addComponent(housingLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(utilitiesInput)
                                .addComponent(entertainmentInput)
                                .addComponent(housingInput, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(groceriesInput)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(transportationLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(transportationInput, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(miscellaneousLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(miscellaneousInput, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housingLabel)
                    .addComponent(housingInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(utilitiesLabel)
                    .addComponent(utilitiesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groceriesLabel)
                    .addComponent(groceriesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entertainmentLabel)
                    .addComponent(entertainmentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportationLabel)
                    .addComponent(transportationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miscellaneousLabel)
                    .addComponent(miscellaneousInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void putInputComponentsInList() {
        componentList = new ArrayList();
        componentList.add(housingInput);
        componentList.add(utilitiesInput);
        componentList.add(groceriesInput);
        componentList.add(entertainmentInput);
        componentList.add(transportationInput);
        componentList.add(miscellaneousInput);
    }
    
    
    private void formatInputComponents() {
        for(javax.swing.JTextField textBox : componentList) {
            InputFilter.giveTextBoxFilterForDollars(textBox);
        }
    }

    
    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        DataHandler database = new DataHandler();        
        for(int textBoxSequence = 0; textBoxSequence < componentList.size(); textBoxSequence++){
            String userInput = componentList.get(textBoxSequence).getText();
            try{
                double dollarAmount = InputValidator.convertStringToDollars(userInput);
                database.writeToSpendingLimits(textBoxSequence,dollarAmount);
            } catch (ParseException e){
                throw new IllegalArgumentException("Unable to write to database");
            }
        }
    }//GEN-LAST:event_saveButtonMouseClicked

    
    private static double returnValidDollarAmount(String input) {
        try {
            return InputValidator.convertStringToDollars(input);
        } catch (ParseException ex) {
            Logger.getLogger(SettingsInitializer.class.getName()).log(Level.SEVERE, null, ex);
            throw new IllegalArgumentException("Can't convert String to double");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entertainmentInput;
    private javax.swing.JLabel entertainmentLabel;
    private javax.swing.JTextField groceriesInput;
    private javax.swing.JLabel groceriesLabel;
    private javax.swing.JTextField housingInput;
    private javax.swing.JLabel housingLabel;
    private javax.swing.JTextField miscellaneousInput;
    private javax.swing.JLabel miscellaneousLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField transportationInput;
    private javax.swing.JLabel transportationLabel;
    private javax.swing.JTextField utilitiesInput;
    private javax.swing.JLabel utilitiesLabel;
    // End of variables declaration//GEN-END:variables
}
