/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPanels;

/**
 *
 * @author Ella
 */
public class AlterBudgetPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlterBudgetPanel
     */
    public AlterBudgetPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterBudgetPanel = new javax.swing.JPanel();
        alterBudgetTitle = new javax.swing.JLabel();
        housingCheckBox = new javax.swing.JCheckBox();
        utilitiesCheckBox = new javax.swing.JCheckBox();
        groceriesCheckBox = new javax.swing.JCheckBox();
        transportationCheckBox = new javax.swing.JCheckBox();
        entertainmentCheckBox = new javax.swing.JCheckBox();
        miscCheckBox = new javax.swing.JCheckBox();
        housingInput = new javax.swing.JTextField();
        utilitiesInput = new javax.swing.JTextField();
        groceriesInput = new javax.swing.JTextField();
        entertainmentInput = new javax.swing.JTextField();
        transportationInput = new javax.swing.JTextField();
        categoriesLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        miscInput = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        alterBudgetPanel.setBackground(new java.awt.Color(255, 255, 255));
        alterBudgetPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        alterBudgetTitle.setText("Alter Budget Constraints");

        housingCheckBox.setText("Housing/Rent");

        utilitiesCheckBox.setText("Utilities");
        utilitiesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilitiesCheckBoxActionPerformed(evt);
            }
        });

        groceriesCheckBox.setText("Groceries");

        transportationCheckBox.setText("Transportation");

        entertainmentCheckBox.setText("Entertainment");

        miscCheckBox.setText("Miscellaneous");

        groceriesInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groceriesInputActionPerformed(evt);
            }
        });

        transportationInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportationInputActionPerformed(evt);
            }
        });

        categoriesLabel.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        categoriesLabel.setText("Category to alter");

        amountLabel.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        amountLabel.setText("New Budget Amount");

        miscInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miscInputActionPerformed(evt);
            }
        });

        submitButton.setText("Submit Changes");

        javax.swing.GroupLayout alterBudgetPanelLayout = new javax.swing.GroupLayout(alterBudgetPanel);
        alterBudgetPanel.setLayout(alterBudgetPanelLayout);
        alterBudgetPanelLayout.setHorizontalGroup(
            alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterBudgetPanelLayout.createSequentialGroup()
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alterBudgetPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(housingCheckBox)
                            .addComponent(miscCheckBox)
                            .addComponent(transportationCheckBox)
                            .addComponent(entertainmentCheckBox)
                            .addComponent(groceriesCheckBox)
                            .addComponent(utilitiesCheckBox)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(categoriesLabel)
                        .addGap(15, 15, 15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                        .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(housingInput, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(utilitiesInput)
                            .addComponent(groceriesInput)
                            .addComponent(entertainmentInput)
                            .addComponent(transportationInput)
                            .addComponent(miscInput))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                        .addComponent(amountLabel)
                        .addGap(90, 90, 90))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                        .addComponent(alterBudgetTitle)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterBudgetPanelLayout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addGap(184, 184, 184))))
        );
        alterBudgetPanelLayout.setVerticalGroup(
            alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterBudgetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alterBudgetTitle)
                .addGap(18, 18, 18)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriesLabel)
                    .addComponent(amountLabel))
                .addGap(19, 19, 19)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housingCheckBox)
                    .addComponent(housingInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(utilitiesCheckBox)
                    .addComponent(utilitiesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groceriesCheckBox)
                    .addComponent(groceriesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entertainmentCheckBox)
                    .addComponent(entertainmentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportationCheckBox)
                    .addComponent(transportationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(miscCheckBox)
                    .addComponent(miscInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(alterBudgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(alterBudgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void utilitiesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilitiesCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilitiesCheckBoxActionPerformed

    private void groceriesInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groceriesInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groceriesInputActionPerformed

    private void transportationInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportationInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportationInputActionPerformed

    private void miscInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miscInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miscInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alterBudgetPanel;
    private javax.swing.JLabel alterBudgetTitle;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JCheckBox entertainmentCheckBox;
    private javax.swing.JTextField entertainmentInput;
    private javax.swing.JCheckBox groceriesCheckBox;
    private javax.swing.JTextField groceriesInput;
    private javax.swing.JCheckBox housingCheckBox;
    private javax.swing.JTextField housingInput;
    private javax.swing.JCheckBox miscCheckBox;
    private javax.swing.JTextField miscInput;
    private javax.swing.JButton submitButton;
    private javax.swing.JCheckBox transportationCheckBox;
    private javax.swing.JTextField transportationInput;
    private javax.swing.JCheckBox utilitiesCheckBox;
    private javax.swing.JTextField utilitiesInput;
    // End of variables declaration//GEN-END:variables
}
